# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  RAM=8148
  CPUS=2
  config.vm.define "staging" do |staging|
    staging.vm.box = "geerlingguy/centos7"
    staging.vm.network "private_network", type: "static", ip: "192.168.100.11"
    staging.vm.hostname = "staging"
    staging.vm.provider "virtualbox" do |v|
      v.name = "staging"
      v.memory = RAM
      v.cpus = CPUS
    end
    staging.vm.provision :shell do |shell|
      shell.path = "install_minikube.sh"
    end
  end
  config.vm.define "production" do |production|
    production.vm.box = "geerlingguy/centos7"
    production.vm.network "private_network", type: "static", ip: "192.168.100.12"
    production.vm.hostname = "production"
    production.vm.provider "virtualbox" do |v|
      v.name = "production"
      v.memory = RAM
      v.cpus = CPUS
    end
    production.vm.provision :shell do |shell|
      shell.path = "install_minikube.sh"
    end
  end
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "geerlingguy/centos7"
    jenkins.vm.network "private_network", type: "static", ip: "192.168.100.10"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "virtualbox" do |v|
      v.name = "jenkins"
      v.memory = RAM
      v.cpus = CPUS
    end
    jenkins.vm.provision :shell do |shell|
      shell.path = "install_master.sh"
    end
  end
end