# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "minikube" do |minikube|
    minikube.vm.box = "geerlingguy/centos7"
    minikube.vm.network "private_network", ip: "192.168.100.10"
    minikube.vm.hostname = "minikube"
    minikube.vm.provider "virtualbox" do |v|
      v.name = "minikube"
      v.memory = 8148
      v.cpus = 4
    end
    minikube.vm.provision :shell do |shell|
      shell.path = "install_minikube.sh"
    end
  end
end
